CREATE TABLE NCI_LABS_MANUAL_LOAD_STAGE
(
  STUDY                VARCHAR2(15),
  PATIENT_ID           VARCHAR2(10),
  OC_PATIENT_POS       VARCHAR2(12),
  LAB_SAMPLE_DATE_RAW  VARCHAR2(20),
  LAB_SAMPLE_TIME_RAW  VARCHAR2(20),
  LAB_TEST_NAME        VARCHAR2(200),
  LAB_TEST_RESULT      VARCHAR2(20),
  LAB_TEST_UOM         VARCHAR2(20),
  LAB_TEST_RANGE       VARCHAR2(80),
  LABORATORY           VARCHAR2(10),
  RECORD_ID            NUMBER(10),
  RECEIVED_DATE        DATE,
  LAB_SAMPLE_DATE      DATE,
  STAGE_DATE           DATE,
  STAGE_USER           VARCHAR2(240),
  STAGE_NOTE           VARCHAR2(200),
  STAGE_ID             NUMBER(10),
  STATUS_FLAG          VARCHAR2(1),
  PROCESS_DATE         DATE,
  PROCESS_USER         VARCHAR2(240),
  LAB_TEST_EVENT       VARCHAR2(40),
  BATCH_ID             NUMBER,
  LAB_TEST_RANGE_LOW   VARCHAR2(30),
  LAB_TEST_RANGE_HIGH  VARCHAR2(30),
  QUALIFYING_VALUE     VARCHAR2(80),
  STATUS_COMMENT       VARCHAR2(200)       DEFAULT 'New Record'
)
/


