CREATE TABLE NCI_LABS_MANUAL_LOAD_BATCHES
(
  BATCH_ID        NUMBER(10),
  SUBMIT_BY       VARCHAR2(30),
  SUBMIT_DATE     DATE,
  JOB_ID          NUMBER(10),
  JOB_START_DATE  DATE,
  JOB_STOP_DATE   DATE,
  BATCH_STATUS    VARCHAR2(1)              DEFAULT 'N',
  STATUS_COMMENT  VARCHAR2(200)            DEFAULT 'New Batch'
)
/

CREATE INDEX NLMLB_IDX ON NCI_LABS_MANUAL_LOAD_BATCHES
(BATCH_ID)
/


