CREATE TABLE NCI_LABS_MANUAL_LOAD_CTL
(
  STUDY                   VARCHAR2(200),
  HOLD_DATA_CHANGES       VARCHAR2(4000),
  AUTO_CHANGE_HOLD_DATA   VARCHAR2(1),
  AUTO_MOVE_TO_STAGE      VARCHAR2(1),
  AUTO_CHANGE_STAGE_DATA  VARCHAR2(1),
  AUTO_MOVE_TO_LOADER     VARCHAR2(1),
  AUTO_LOAD_TO_OC         VARCHAR2(1),
  STAGE_DATA_CHANGES      VARCHAR2(4000),
  INBOUND_STUDY           VARCHAR2(200),
  CREATE_USER             VARCHAR2(30),
  CREATE_DATE             DATE,
  MODIFY_USER             VARCHAR2(30),
  MODIFY_DATE             DATE
)
/

CREATE UNIQUE INDEX ML_CTL_PK ON NCI_LABS_MANUAL_LOAD_CTL
(STUDY)
/


