CREATE OR REPLACE FUNCTION redact (
   p_STUDY       VARCHAR2,
   p_CDE_ID      VARCHAR2,
   p_CDE_VERSION VARCHAR2)
   RETURN VARCHAR2
IS
   v_DUMMY VARCHAR2(1);
BEGIN
   SELECT 'X'
     INTO v_DUMMY
     FROM STUDY_PRIVATE_CDE
 WHERE CDE_ID = p_CDE_ID
   AND CDE_VERSION = p_CDE_VERSION
   AND (STUDY = p_STUDY or STUDY = 'ALL');

  RETURN 'Y';
EXCEPTION
   WHEN NO_DATA_FOUND THEN
     RETURN 'N';
END;
/


