INSERT INTO csm_role_privilege(role_id, privilege_id)
VALUES (
(select Role_id      from CSM_ROLE       where ROLE_NAME      = 'registrar'),
(select PRIVILEGE_ID from CSM_PRIVILEGE  where PRIVILEGE_NAME = 'CCC3D_ENROLLPATIENT_SERVICE')
);

INSERT INTO csm_role_privilege(role_id, privilege_id)
VALUES (
(select Role_id      from CSM_ROLE       where ROLE_NAME      = 'lab_data_user'),
(select PRIVILEGE_ID from CSM_PRIVILEGE  where PRIVILEGE_NAME = 'CCC3D_LOADLABS_SERVICE')
);

INSERT INTO csm_role_privilege(role_id, privilege_id)
VALUES (
(select Role_id      from CSM_ROLE       where ROLE_NAME      = 'data_analyst'),
(select PRIVILEGE_ID from CSM_PRIVILEGE  where PRIVILEGE_NAME = 'CCC3D_GETSTUDYCDES_SERVICE')
);

INSERT INTO csm_role_privilege(role_id, privilege_id)
VALUES (
(select Role_id      from CSM_ROLE       where ROLE_NAME      = 'registrar'),
(select PRIVILEGE_ID from CSM_PRIVILEGE  where PRIVILEGE_NAME = 'CCC3D_ISVALIDSTUDY_SERVICE')
);

INSERT INTO csm_role_privilege(role_id, privilege_id)
VALUES (
(select Role_id      from CSM_ROLE       where ROLE_NAME      = 'lab_data_user'),
(select PRIVILEGE_ID from CSM_PRIVILEGE  where PRIVILEGE_NAME = 'CCC3D_ISVALIDSTUDY_SERVICE')
);

INSERT INTO csm_role_privilege(role_id, privilege_id)
VALUES (
(select Role_id      from CSM_ROLE       where ROLE_NAME      = 'data_analyst'),
(select PRIVILEGE_ID from CSM_PRIVILEGE  where PRIVILEGE_NAME = 'CCC3D_ISVALIDSTUDY_SERVICE')
);



INSERT INTO CSM_PG_PE(PROTECTION_GROUP_ID, PROTECTION_ELEMENT_ID)
VALUES (
(select PROTECTION_GROUP_ID   from CSM_PROTECTION_GROUP    where PROTECTION_GROUP_NAME   = 'CCC3D_ISVALIDSTUDY_SERVICE'),
(select PROTECTION_ELEMENT_ID from CSM_PROTECTION_ELEMENT  where PROTECTION_ELEMENT_NAME = 'CCC3D_ISVALIDSTUDY_SERVICE')
);

INSERT INTO CSM_PG_PE(PROTECTION_GROUP_ID, PROTECTION_ELEMENT_ID)
VALUES (
(select PROTECTION_GROUP_ID   from CSM_PROTECTION_GROUP    where PROTECTION_GROUP_NAME   = 'CCC3D_GETSTUDYCDEDATA_SERVICE'),
(select PROTECTION_ELEMENT_ID from CSM_PROTECTION_ELEMENT  where PROTECTION_ELEMENT_NAME = 'CCC3D_GETSTUDYCDEDATA_SERVICE')
);

INSERT INTO CSM_PG_PE(PROTECTION_GROUP_ID, PROTECTION_ELEMENT_ID)
VALUES (
(select PROTECTION_GROUP_ID   from CSM_PROTECTION_GROUP    where PROTECTION_GROUP_NAME   = 'CCC3D_LOADLABS_SERVICE'),
(select PROTECTION_ELEMENT_ID from CSM_PROTECTION_ELEMENT  where PROTECTION_ELEMENT_NAME = 'CCC3D_LOADLABS_SERVICE')
);

INSERT INTO CSM_PG_PE(PROTECTION_GROUP_ID, PROTECTION_ELEMENT_ID)
VALUES (
(select PROTECTION_GROUP_ID   from CSM_PROTECTION_GROUP    where PROTECTION_GROUP_NAME   = 'CCC3D_ENROLLPATIENT_SERVICE'),
(select PROTECTION_ELEMENT_ID from CSM_PROTECTION_ELEMENT  where PROTECTION_ELEMENT_NAME = 'CCC3D_ENROLLPATIENT_SERVICE')
);

