CREATE TABLE DCAPI_USER_CREDENTIALS
(
  UNAME          VARCHAR2(50),
  PWORD          VARCHAR2(400),
  STATUS         VARCHAR2(100),
  C3D_TNS_ENTRY  VARCHAR2(100)
);

INSERT INTO DCAPI_USER_CREDENTIALS ( UNAME, PWORD, STATUS, C3D_TNS_ENTRY ) 
VALUES ( 'C3DDCAPIUSER', 'nB5wkF1GNcs=', 'ACTIVE', 'OCDEV45.NCI.NIH.GOV');

CREATE TABLE STUDY_CDES_CTL
(
  STUDY           VARCHAR2(100)            NOT NULL,
  REFERENCE_CODE  VARCHAR2(100)            NOT NULL,
  CDE             VARCHAR2(400)            NOT NULL
);

INSERT INTO STUDY_CDES_CTL ( STUDY, REFERENCE_CODE, CDE ) 
VALUES ( 'SMOKE_TEST', 'PATIENT_ID_CDE', 'CDE_ID:2003301VERSION:3.0');

INSERT INTO STUDY_CDES_CTL ( STUDY, REFERENCE_CODE, CDE ) 
VALUES ( 'SMOKE_TEST', 'NCI_INST_CD_CDE', 'CDE_ID:2003707VERSION:3');

INSERT INTO STUDY_CDES_CTL ( STUDY, REFERENCE_CODE, CDE ) 
VALUES ( 'SMOKE_TEST', 'PT_INITS', 'CDE_ID:2001039VERSION:4.0');

INSERT INTO STUDY_CDES_CTL ( STUDY, REFERENCE_CODE, CDE ) 
VALUES ( 'SMOKE_TEST', 'PT_DOB', 'CDE_ID:793VERSION:4.0');

INSERT INTO STUDY_CDES_CTL ( STUDY, REFERENCE_CODE, CDE ) 
VALUES ( 'SMOKE_TEST', 'PT_GENDER', 'CDE_ID:62VERSION:6.0');

INSERT INTO STUDY_CDES_CTL ( STUDY, REFERENCE_CODE, CDE ) 
VALUES ( 'SMOKE_TEST', 'REG_DATE', 'CDE_ID:2171VERSION:4.0');

CREATE TABLE STUDY_PRIVATE_CDE
(
  STUDY        VARCHAR2(15 BYTE)                NOT NULL,
  CDE_ID       VARCHAR2(40 BYTE)                NOT NULL,
  CDE_VERSION  VARCHAR2(30 BYTE)                NOT NULL
);

INSERT INTO STUDY_PRIVATE_CDE ( STUDY, CDE_ID, CDE_VERSION ) 
VALUES ( 'SMOKE_TEST', '2003301', '3.0');

CREATE TABLE STUDY_SECURITY_LEVEL
(
  STUDY          VARCHAR2(15 BYTE)              NOT NULL,
  ACCESS_METHOD  VARCHAR2(10 BYTE)              NOT NULL
);

INSERT INTO STUDY_SECURITY_LEVEL ( STUDY, ACCESS_METHOD ) 
VALUES ( 'ALL', 'PRIVATE');

INSERT INTO STUDY_SECURITY_LEVEL ( STUDY, ACCESS_METHOD ) 
VALUES ( 'SMOKE_TEST', 'PUBLIC');


CREATE TABLE C3D_USER
(
  C3D_USERNAME       VARCHAR2(50),
  C3D_PASSWORD       VARCHAR2(50),
  EXTRNL_LOGIN_NAME  VARCHAR2(500) NOT NULL,
  UPDATE_DATE        DATE          DEFAULT SYSDATE               NOT NULL
);


CREATE TABLE CLINICAL_CONNECTOR_PROPERTIES
(
  PROPERTY_KEY    VARCHAR2(50 BYTE)             NOT NULL,
  PROPERTY_VALUE  VARCHAR2(50 BYTE)             NOT NULL
);


CREATE UNIQUE INDEX CCP_PK ON CLINICAL_CONNECTOR_PROPERTIES
(PROPERTY_KEY);


Insert into CLINICAL_CONNECTOR_PROPERTIES   (PROPERTY_KEY, PROPERTY_VALUE)
 Values ('csm.application.name', 'CTMS_SUITE');

Insert into CLINICAL_CONNECTOR_PROPERTIES   (PROPERTY_KEY, PROPERTY_VALUE)
 Values   ('csm.enroll.role', 'registrar');

Insert into CLINICAL_CONNECTOR_PROPERTIES   (PROPERTY_KEY, PROPERTY_VALUE)
 Values   ('csm.lab.role', 'lab_data_user');

Insert into CLINICAL_CONNECTOR_PROPERTIES   (PROPERTY_KEY, PROPERTY_VALUE)
 Values   ('enrollPatientManager.saveBirthDate.value', 'false');

Insert into CLINICAL_CONNECTOR_PROPERTIES   (PROPERTY_KEY, PROPERTY_VALUE)
 Values   ('enrollPatientManager.saveGender.value', 'false');

Insert into CLINICAL_CONNECTOR_PROPERTIES   (PROPERTY_KEY, PROPERTY_VALUE)
 Values   ('enrollPatientManager.saveInitials.value', 'true');

Insert into CLINICAL_CONNECTOR_PROPERTIES   (PROPERTY_KEY, PROPERTY_VALUE)
 Values   ('enrollPatientManager.saveEnrollmentDate.value', 'false');

Insert into CLINICAL_CONNECTOR_PROPERTIES   (PROPERTY_KEY, PROPERTY_VALUE)
 Values   ('enrollPatientService.useCSM', 'true');

Insert into CLINICAL_CONNECTOR_PROPERTIES   (PROPERTY_KEY, PROPERTY_VALUE)
 Values   ('loadLabsService.useCSM', 'false');



