CREATE TABLE C3D_MAIL_MESSAGE_CTL
(
  UTIL_CODE     VARCHAR2(15)               NOT NULL,
  ALERT_TYPE    VARCHAR2(10)               NOT NULL,
  MESSAGE_TYPE  VARCHAR2(10)               NOT NULL,
  MESSAGE_TEXT  VARCHAR2(4000)             NOT NULL,
  CREATE_USER   VARCHAR2(30),
  CREATE_DATE   DATE,
  MODIFY_USER   VARCHAR2(30),
  MODIFY_DATE   DATE
)
/

CREATE OR REPLACE TRIGGER CMM_BU 
 BEFORE UPDATE 
 ON C3D_MAIL_MESSAGE_CTL
 REFERENCING OLD AS OLD NEW AS NEW 
 FOR EACH ROW 
-- PL/SQL Block
BEGIN 
 :new.MODIFY_USER := substr(user,1,30); 
 :new.MODIFY_DATE := sysdate; 
END;
/

CREATE OR REPLACE TRIGGER CMM_BI 
 BEFORE INSERT 
 ON C3D_MAIL_MESSAGE_CTL
 REFERENCING OLD AS OLD NEW AS NEW 
 FOR EACH ROW 
-- PL/SQL Block
BEGIN 
 if :new.CREATE_USER IS NULL THEN 
   :new.CREATE_USER := substr(user,1,30); 
 END IF; 
 :new.CREATE_DATE := sysdate; 
END;
/

INSERT INTO C3D_MAIL_MESSAGE_CTL ( UTIL_CODE, ALERT_TYPE, MESSAGE_TYPE, MESSAGE_TEXT )
VALUES ('AUTO_LOADER', 'SUCCESS', 'CLOSING', 'This is the closing text for the AUTO_LOADER - SUCCESS Message')
/

INSERT INTO C3D_MAIL_MESSAGE_CTL ( UTIL_CODE, ALERT_TYPE, MESSAGE_TYPE, MESSAGE_TEXT )
VALUES ('AUTO_LOADER', 'FAILURE', 'OPENING', 'The AutoLoader process of Lab Loader has experienced a FAILURE on OCDEV.')
/

INSERT INTO C3D_MAIL_MESSAGE_CTL ( UTIL_CODE, ALERT_TYPE, MESSAGE_TYPE, MESSAGE_TEXT )
VALUES ('AUTO_LOADER', 'FAILURE', 'CLOSING', 'Please contact the C3D Utility Support Team for further information.')
/

INSERT INTO C3D_MAIL_MESSAGE_CTL ( UTIL_CODE, ALERT_TYPE, MESSAGE_TYPE, MESSAGE_TEXT )
VALUES ('C3D_MAILER', 'FAILURE', 'OPENING', 'The C3D Mail Utility encountered an error while processing a request.')
/

INSERT INTO C3D_MAIL_MESSAGE_CTL ( UTIL_CODE, ALERT_TYPE, MESSAGE_TYPE, MESSAGE_TEXT )
VALUES ('C3D_MAILER', 'WARNING', 'OPENING', 'The C3D Mail Utility encountered a WARNING while processing a request.')
/

INSERT INTO C3D_MAIL_MESSAGE_CTL ( UTIL_CODE, ALERT_TYPE, MESSAGE_TYPE, MESSAGE_TEXT )
VALUES ('ALL', 'ALL', 'POSTSCRIPT', 'NOTE: This is an automated e-mail service.  Do not respond to this e-mail directly.  Contact #CONTACT# if you have any quetions.')
/

